:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Notes on testing/dev to support repo merge

toc::[]

== Spin up dev environment (if nothing serious has changed)

All we need is the API running, so:

[bash,source]
----
supervisord -c supervisord/backend.conf
----

[#switchdb]
== Switch the database that is running in dev environment

If API is running, stop it.

This switches back to the base db in fixtures.
Change the db name on the end of the 3rd line as needed.

[source,bash]
----
mysql -h 127.0.0.1 -u as -pas123 -e "DROP DATABASE archivesspace"
mysql -h 127.0.0.1 -u as -pas123 -e "CREATE DATABASE IF NOT EXISTS archivesspace DEFAULT CHARACTER SET utf8mb4"
mysql --host=127.0.0.1 --port=3306  -u root -p123456 archivesspace < ~/code/as/repo-move/spec/support/fixtures/base.sql
./build/run db:migrate
supervisord -c supervisord/backend.conf
----


== Export repo from the dev environment

Load the db containing the repo we want to export, as <<switchdb,shown above>>.
Then:

IMPORTANT: Change repo number if it isn't 2

[source,bash]
----
./export.sh http://localhost:4567/ 2 admin admin
----

JSON is saved to `./exports` directory.
Change the name of the exported file to indicate the test db/repo it was exported from.

== Import exported JSON into base

Switch back to base db, as <<switchdb,shown above>>.

[source,bash]
.*Create a new repo to import into*
----
./create_repository.sh http://localhost:4567/ admin admin merge_1
----

IMPORTANT: Note the id of the repo created by the previous command.

[source,bash]
----
./import.sh http://localhost:4567 3 admin admin merge_1_repo_2.json
----
